version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - .:/opt/app/api
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: goair
      MYSQL_USER: goair
      MYSQL_PASSWORD: goair


